### ISSUE TITLE
Document unsafety of functions with 'static-containing return types.

### ISSUE THREAD

**Issue by tormol** [nagisa/rust_libloading#46]
Return values from functions that contain `'static` lifetimes are not reduced to the lifetime of the loaded library, and can outlive it.
Preventing this is probably impossible (especially when the `'static` is hidden inside a type like `Wrapper(&'static u32)`), but the docs could warn about it.

Here's one example that segfaults:

Cargo.toml:
```toml
[package]
name = "unsafe_libloading"
version = "0.0.0"

[lib]
path = "lib.rs"
name = "loadee"
crate-type = ["dylib"]

[[bin]]
name = "loader"
path = "main.rs"

[dependencies]
libloading = "0.5"
```

lib.rs:
```rust
#[no_mangle]
pub fn get_str() -> &'static str {
    "Hello, world"
}
```

main.rs:
```rust
extern crate libloading;

fn main() -> libloading::Result<()> {
    let lib = libloading::Library::new("libloadee.so")?;
    let return_value: &'static str = {
        let fun: libloading::Symbol<extern fn()->&'static str> = unsafe{ lib.get(b"get_str") }?;
        fun()
    };
    drop(lib);
    println!("return value: {}", return_value);
    Ok(())
}
```

I assume this issue also applies to loaded global variables, but dereferencing those produced bogus values even without dropping `lib`:

lib.rs:
```rust
#[no_mangle]
pub static REF: &'static u16 = &19;
```

main.rs:
```rust
extern crate libloading;

fn main() -> libloading::Result<()> {
    let lib = libloading::Library::new("libloadee.so")?;
    let var: libloading::Symbol<&'static u16> = unsafe{ lib.get(b"REF") }?;
    let dereferenced: u16 = **ref;
    println!("variable: {} = 0x{:x}", dereferenced, dereferenced);
    Ok(())
}
```
prints "variable: 27312 = 0x6ab0"
